As my little life developed, so did the lives around me. My parents gave birth to a second child, my sister Amanda. She too had a troubled birth. Amanda was in the hospital for weeks at a time during infancy for various health issues due to complications from drug use. Her survival was never guaranteed. At times it looked like she wasn’t going to make it. With medical help, luck, and her own tenacity she pulled through. 

Once my sister arrived home to stay, i became VERY protective of her. i wouldn’t let her out of my sight. i was always around when people who weren’t in my immediate family would want to hold her or approach her, saying things like, “Be careful with my sister, please!” i’m not entirely sure where this instinct came from. i felt like we were connected in a deep way, even from a young age. My toddler self was almost a third parent (and in all honesty, more like a second parent depending on how much care she was being given at any time).

Over time this instinct calmed somewhat as i saw Amanda begin to grow. She was noisy as babies are, but she was also exploratory and curious. i loved to play with her and her toys, find ways to be part of her care during bath time, changing, and feeding. i found a sense of peace in being able to help my mother care for my baby sister. The bond i was building with Amanda came naturally to me. It made me feel like the family around me was more whole in a way i hadn’t known until she arrived.

Once Amanda had reached her toddler stage, things changed dramatically. Her attitude became outwardly combative. She regularly challenged the established territorial hierarchy. Amanda was always ready for a fight of some kind, or to make one if one wasn’t available. Oftentimes Amanda would wake up earlier than everyone else, sneak into my room, stick two fingers up my nostrils and scream at me to wake up as she pulled my nose upward. The two of us began to fight more than we would play together, and in time i found myself pulling away from her, too. i wanted to find camaraderie with her, to have a built-in best friend i could share myself with. Instead, i wound up living with a hostile enemy.  

Things didn’t improve over time. Our relationship as siblings steadily grew more and more distant. Amanda found new ways of expanding her emotional territory into the relationships and lives of everyone around her. Her birth may have been a part of parent’s overall decision to divorce. As i’ve mentioned, the mutual physical and emotional abuse my parents put one another through, their individual difficulty with maintaining steady work, my uncle’s death, my aunt’s death (my mother’s sister passed away when i was 4), and so many other compounding emotional issues finally came to a head. My parents must have figured there was no point in trying to maintain a marriage that was so destructive. 

When it finally ended Amanda was 5, i was 7, and we were in the care of our mother who moved us out of the house we grew up in. We moved into an apartment directly next door to my Grandma, my Mom’s Mom. Dad got visitation rights to see Amanda and myself which Mom honored. Those were awkward, strained, and unfulfilling. They quickly became another emotional burden i had to carry with me.

Mom’s mental state cast a shadow over our little home. She wasn’t able to be around much because she was working, but her presence was felt in little ways. There was a constant exertion of control that permeated every waking moment in the apartment. Mom made a point to overreach into me and my sibling’s lives whenever she could, though much of the time Amanda and i were in Grandma’s care. This often looked like fighting battles in our schools despite the problems being minor, childish squabbles. i remember many a teacher’s meeting based on little more than me complaining about me being bullied by someone and there being no evidence to back it up. If anything these meetings were more disruptive than productive. Nothing meaningful or lasting ever came from them aside from yet more emotional strain on the entire family.

To her credit, Mom also tried to connect with us both when she could. We would sometimes go to play in nearby parks, get treats from ice cream shops, or be gifted small toys or books to keep us entertained. That said, i never felt like i could count on my Mom for emotional stability. i never saw her practice being calm. All i ever heard her talk about were complaints about anything and everything that happened to her. Dad was often the subject du jour on any given day. Life was one long blur of battle after battle, if only in her mind. My mother’s default mode of operation was to always be primed and ready for battle. That is what i grew up seeing most consistently. As a result, i began to emulate this readiness in my own mindset. 

My struggles within familial hierarchy were minimal at best. i made a point to never have a presence that demanded attention. i deliberately shrank myself and my needs so that i wouldn’t be more of a problem than necessary. My sister was causing more than enough problems for the two of us. i would sometimes do things i knew would get me in trouble and blame them on Amanda instead of taking the fall myself. i can’t imagine the impact this had on my sister. i was far from totally innocent as a child, i just knew how i could get away with things. 

My hollow existence was marred not only by the constant fear of turmoil that arose daily in the home, but by a realization regarding myself rooted deep within a place i hadn’t yet discovered. i was surrounded by women of all ages, sizes, capabilities, initiatives, and priorities every day. It was myself, my mom, my sister, my Grandma, and for a time my cousin Julie living under separate roofs divided only by 6 feet of concrete between the front doors. i was growing up trying to understand my place in a matriarchal family system as a “boy”. My experiences led me to a strange understanding of what it meant to be masculine as opposed to feminine. 

Because of my home life dynamic, i always had an easier time connecting to femme hierarchies of social order. There were unspoken rulesets for living i came to understand through all my quiet observation as i shrank into the background. There was no single authority figure that commanded Amanda, Julie, and myself. My Mom and Grandma took turns watching over us, helping us, and reprimanding us. The three of us acted out in a lot of ways back then. Julie was suffering the loss of her mother (my aforementioned aunt) and her own family breaking apart as a teenager. There was no shortage of pain that permeated our five hearts and minds. Mom and Grandma often gave conflicting:overriding instructions on how to handle the issues we three faced. Obviously all of that guidance came from a feminine perspective. Julie and Amanda had a better understanding of what those messages meant. i would often look to them for guidance or followed their example. 

Eventually this emotional connection started to show itself in more outward, physical ways. i would dress up in my sister’s and cousin’s clothes when they weren’t around. It helped me feel good about myself, which in turn helped me feel more in tune with my emotional needs (since they weren’t being met elsewhere). i specifically remember an instance where Julie and Amanda convinced me (not very much against my will, i’ll admit i was scared but excited) to let them dress me up and put makeup on me. i paraded down the staircase in my Grandma’s tiny apartment like i was the belle of the ball. i was elated and more comfortable around the house that day than any other i could remember at the time. It was amazing. 

Still, i hid that part of me away. The consequences i feared were more real to me than the joy and relief i felt when i acted on my feelings. i began living a secret life behind barely cracked open doors with my eyes staring out, unblinking. My footsteps became soft, my motions sneaky. Every sound i heard was a reason for alarm. i learned to carry myself in even smaller and more hidden ways than ever before, risking everything for even a moment of hidden contentment i could treasure in the corners of my mind. 

That was my emotional-territorial lot in life during childhood. i relegated myself to the background so others could use the emotional space. i took that background position to be an observer in my own world since i had no dominant masculine figure to model myself after. i didn’t know at the time that a masculine figure wasn’t necessary. All i knew was my Dad wasn’t around. 

There was little room for me to exert myself in any territorial space since Mom, Amanda, Julie, and Grandma were constantly at odds with one another. i was the quintessential example of Friendly Weakness. Honestly, i felt like weakness as a concept personified. Milquetoast. Ineffectual. i was inoffensive, spineless, sad, and though surrounded by my own family dreadfully alone. There wasn’t much point in trying to live any other way, even if my hidden joys held the promise of something better.
